version: "3"
services:
  app:
    container_name: "qt3.3_demo"
    hostname: "qt3.3"
    image: qt3.3_demo:latest
    build:
      context: .
    environment:
      - DISPLAY=unix${DISPLAY}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
